cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:bouquet_id>/', views.cart_add, name='cart_add'),
    path('update/<int:item_id>/', views.cart_update, name='cart_update'),
    path('remove/<int:bouquet_id>/', views.cart_remove, name='cart_remove'),
    path('decrease/<int:bouquet_id>/', views.cart_decrease, name='cart_decrease'),
    path('clear/', views.cart_clear, name='cart_clear'),
    path('apply-discount/', views.apply_discount, name='apply_discount'),
]

itproger/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('discount/',include('discount.urls')),
    path('', include('pages.urls')),
    
    # URLs для авторизации
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('register/', include('users.urls')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('',views.index, name='catalog_flow'),
    path('description/<int:bouquet_id>/',views.description, name='description'),
]

main/models.py
from django.db import models

class Bouquet(models.Model):
    TYPE_CHOICES = [
        ('box', 'В коробке'),
        ('paper', 'В бумаге'),
    ]

    name = models.CharField(max_length=100, verbose_name="Название букета")
    price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name="Цена")
    bouquet_type = models.CharField(max_length=10, choices=TYPE_CHOICES, default='paper', verbose_name="Тип упаковки")
    flowers_sort = models.CharField(max_length=255, verbose_name="Сорт цветов", default='')
    description = models.TextField(blank=True, verbose_name="Описание")
    image = models.ImageField(upload_to='bouquets/', blank=False, null=False, verbose_name="Изображение")

    class Meta:
        verbose_name = "Букет"
        verbose_name_plural = "Букеты"

    def __str__(self):
        return self.name

main/views.py
from django.shortcuts import render
from .models import Bouquet
from cart.models import Cart
from django.shortcuts import render, get_object_or_404
from django.db.models import Q


def index(request):
    bouquets = Bouquet.objects.all()
    query = request.GET.get('q')
    if query:
        query_lower = query.lower()
        type_mapping = {
            'бумага': 'paper',
            'коробка': 'box',
        }
        q_objects = Q()
        q_objects |= Q(name__iregex=query)
        q_objects |= Q(description__iregex=query)
        q_objects |= Q(flowers_sort__iregex=query)
        for ru_term, db_value in type_mapping.items():
            if ru_term in query_lower:
                q_objects |= Q(bouquet_type=db_value)
                break
        
        bouquets = bouquets.filter(q_objects)
    packaging = request.GET.get('packaging')
    if packaging and packaging != 'all':
        bouquets = bouquets.filter(bouquet_type=packaging)
    sort = request.GET.get('sort', 'default')
    if sort == 'price_asc':
        bouquets = bouquets.order_by('price')
    elif sort == 'price_desc':
        bouquets = bouquets.order_by('-price')
    cart_quantities = {}
    if request.user.is_authenticated:
        try:
            cart = Cart.objects.get(user=request.user)
            for bouquet in bouquets:
                cart_quantities[bouquet.id] = cart.get_item_quantity(bouquet.id)
        except Cart.DoesNotExist:
            pass
    context = {
        'bouquets': bouquets,
        'cart_quantities': cart_quantities,
        'search_query': query,
        'current_sort': sort,
    }
    return render(request, 'main/catalog_flow.html', context)

def description(request, bouquet_id):
    bouquet = get_object_or_404(Bouquet, id=bouquet_id)
    cart_quantities = {}
    if request.user.is_authenticated:
        try:
            cart = Cart.objects.get(user=request.user)
            # Можно получить количество для текущего букета
            cart_quantities[bouquet.id] = cart.get_item_quantity(bouquet.id)
        except Cart.DoesNotExist:
            pass
    context = {
        'bouquet': bouquet,
        'cart_quantities': cart_quantities,
    }
    return render(request, 'main/description.html', context)

main/templates/main/catalog_flow.html
{% extends 'main/layout.html' %}
{% load static %}
{% load catalog_extras %}

{%block title%}Bloom{% endblock %}

{% block content %}
<div class="features">
    <h1>Каталог</h1>
    <p>Цветы — нежные и хрупкие создания природы. Они радуют глаз яркостью цвета и элегантностью бутонов. Цветы многогранны, и каждый может отыскать для себя тот, который ему нравится — любого размера, вида, цвета.</p>
    <div class="forms-container">
        <div class="filter-left">
            <form method="get" style="display: inline-block;">
                {% if search_query %}
                    <input type="hidden" name="q" value="{{ search_query }}">
                {% endif %}
                {% if current_sort %}
                    <input type="hidden" name="sort" value="{{ current_sort }}">
                {% endif %}
                <label for="packaging">Тип упаковки:</label>
                <select name="packaging" id="packaging" class="sort-form" onchange="this.form.submit()">
                    <option value="all" {% if not request.GET.packaging or request.GET.packaging == 'all' %}selected{% endif %}>Все</option>
                    <option value="paper" {% if request.GET.packaging == 'paper' %}selected{% endif %}>Бумага</option>
                    <option value="box" {% if request.GET.packaging == 'box' %}selected{% endif %}>Коробка</option>
                </select>
            </form>
            <form method="get">
                {% if search_query %}
                    <input type="hidden" name="q" value="{{ search_query }}">
                {% endif %}
                <label for="sort">Цена:</label>
                <select name="sort" id="sort" class="sort-form" onchange="this.form.submit()">
                    <option value="default" {% if current_sort == 'default' %}selected{% endif %}>По умолчанию</option>
                    <option value="price_asc" {% if current_sort == 'price_asc' %}selected{% endif %}>По возрастанию</option>
                    <option value="price_desc" {% if current_sort == 'price_desc' %}selected{% endif %}>По убыванию</option>
                </select>
            </form>
        </div>
        <div class="filter-right">
            <form method="get" action="{% url 'catalog_flow' %}">
                <input type="text" name="q" class="search" placeholder="Поиск..." value="{{ search_query|default:'' }}">
                <button type="submit" class="btn btn-light">Найти</button>
            </form>
        </div>
    </div>
        <p class="result_right">Найдено: {{ bouquets|length }}</p>
    <div class="catalog_container">
        {% for el in bouquets %}
        <div class="catalog_cont">
            <img src="{{ el.image.url }}" alt="...">
            <a href="{% url 'description' el.id %}" class="catalog-link" target="_blank">
                <h3 class="catalog_name">{{ el.name }}</h3>
            </a>
            
            <div class="price-cart-container">
                <p class="catalog_price">{{ el.price }} руб.</p>
                
                {% if user.is_authenticated %}
                {% with quantity=cart_quantities|get_item:el.id %}
                {% if quantity > 0 %}
                    <p class="added-to-cart-msg add-to-cart-form">Товар добавлен в корзину</p>
                {% else %}
                <form method="post" action="{% url 'cart:cart_add' el.id %}" class="add-to-cart-form" data-product-id="{{ el.id }}">
                {% csrf_token %}
                    <button type="submit" class="btn btn-light"><i class="fa-solid fa-cart-plus"></i> Добавить в корзину</button>
                </form>
                {% endif %}
                {% endwith %}
                {% else %}
                <a href="{% url 'login' %}?next={{ request.path }}" class="btn btn-light">
                    <i class="fa-solid fa-cart-plus"></i> Войдите чтобы купить
                </a>
                {% endif %}
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<script>
  document.addEventListener('visibilitychange', function() {
    if (!document.hidden) {
      location.reload();
    }
  });
</script>
{% endblock %}

main/templates/main/description.html
{% extends 'main/layout.html' %}
{% load static %}
{% load catalog_extras %}

{%block title%}{{ bouquet.name }} - Bloom{% endblock %}

{% block content %}
<div class="features">
    <div class="row">
        <a href="{% url 'catalog_flow' %}" class="btn btn-dark" style="width: auto;">
            <i class="fa-solid fa-arrow-left"></i> Вернуться в каталог
        </a>           
    </div>
    <div class="container">
<div id="image-container" class="image-container">
  <img src="{{ bouquet.image.url }}" alt="{{ bouquet.name }}" class="description_img">
  <div class="description_gradient"></div>
</div>
<button id="toggle-image" class="collapse_image">Развернуть</button>

        <h1 class= "col-md-9">{{ bouquet.name }}</h1>
        <p>{{ bouquet.price }} руб.</p>
        <h3>Описание</h3>
        <p>{{ bouquet.description }}</p>
        <h3>Тип упаковки</h3>
        <p>{{ bouquet.get_bouquet_type_display }}</p>
        <h3>Состав</h3>
        <p>{{ bouquet.flowers_sort }}</p>
        {% if user.is_authenticated %}
        {% with quantity=cart_quantities|get_item:bouquet.id %}
        {% if quantity > 0 %}
            <p class="added-to-cart-msg add-to-cart-form">Товар добавлен в корзину</p>
        {% else %}
        <form method="post" action="{% url 'cart:cart_add' bouquet.id %}" class="add-to-cart-form" data-product-id="{{ bouquet.id }}">
            {% csrf_token %}
            <button type="submit" class="settings-btn description_btn"><i class="fa-solid fa-cart-plus"></i> Добавить в корзину</button>
        </form>

        {% endif %}
        {% endwith %}
        {% else %}
        <a href="{% url 'login' %}?next={{ request.path }}" class="btn btn-light">
            <i class="fa-solid fa-cart-plus"></i> Войдите чтобы купить
        </a>
        {% endif %}
    </div>
</div>
<script>
  document.addEventListener('visibilitychange', function() {
    if (!document.hidden) {
      location.reload();
    }
  });
  const button = document.getElementById('toggle-image');
const container = document.getElementById('image-container');

button.addEventListener('click', () => {
  container.classList.toggle('expanded');
  if (container.classList.contains('expanded')) {
    button.textContent = 'Свернуть';
  } else {
    button.textContent = 'Развернуть';
  }
});


</script>

{% endblock %}

main/templates/main/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Bloom{% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="{% static 'main/img/logo.png' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="{%static 'main/css/main.css' %}">
</head>
<body>
  <script src="{% static 'main/js/main.js' %}"></script>
  <button id="toggle-menu" aria-label="Toggle menu" class="menu-toggle">
    <i class="fa-solid fa-bars"></i>
  </button>
    <aside>
        <img src="{%static 'main/img/logo.png'%}">
        <span class="logo">bloom</span>
        <ul>            
            <a href="{% url 'catalog_flow' %}"><li><i class="fa-solid fa-house" style="color: #568dc9;"></i> Главная</li></a>
            {% if user.is_authenticated %}
            <a href="{% url 'profile' %}"><li><i class="fa-solid fa-user" style="color: #568dc9;"></i> Профиль</li></a>
            <a href="{% url 'cart:cart_detail' %}"><li><i class="fa-solid fa-basket-shopping" style="color: #568dc9;"></i> Корзина</li></a>
            {% endif %}
            <a href="{% url 'about' %}"><li><i class="fa-solid fa-address-card" style="color: #568dc9;"></i> О компании</li></a>
            <a href="{% url 'discount_home' %}"><li><i class="fa-solid fa-tags" style="color: #568dc9;"></i> Акции</li></a>
            <a href="{% url 'contacts' %}"><li><i class="fa-solid fa-phone" style="color: #568dc9;"></i> Контакты</li></a>
            <a href="{% url 'faq' %}"><li><i class="fa-solid fa-circle-question" style="color: #568dc9;"></i> FAQ</li></a>
            {% if user.is_authenticated %}
            <button type="button" class="logout-btn" data-bs-toggle="modal" data-bs-target="#logoutModal"><i class="fa-solid fa-right-from-bracket" style="color: #568dc9;"></i> Выход</button>
            {% else %}
            <a href="{% url 'login' %}"><li><i class="fa-solid fa-right-to-bracket"></i> Войти</li></a>
            {% endif %}
        </ul>
    </aside>
    <main>
        {% block content %}
        {% endblock %}
    </main>

    <div class="modal fade" id="logoutModal" tabindex="-1" aria-labelledby="logoutModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="logoutModalLabel">Подтвердите выход</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
        </div>
        <div class="modal-body">
          Уверены, что хотите выйти?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-light" data-bs-dismiss="modal">Отмена</button>
          <form method="post" action="{% url 'logout' %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-dark">Выйти</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <footer>
      <nav>
          <a href="{% url 'catalog_flow' %}">Главная</a>
          <a href="{% url 'about' %}">О компании</a>
          <a href="{% url 'discount_home' %}">Акции</a>
          <a href="{% url 'contacts' %}">Контакты</a>
          <a href="{% url 'faq' %}">FAQ</a>
      </nav>
  </footer>
  <button id="scrollToTopBtn" class="scroll-to-top">
      <i class="fa-solid fa-chevron-up"></i>
  </button>
  <script>
  document.addEventListener('DOMContentLoaded', function() {
      const scrollToTopBtn = document.getElementById('scrollToTopBtn');
      
      if (scrollToTopBtn) {
          window.addEventListener('scroll', function() {
              if (window.pageYOffset > 300) {
                  scrollToTopBtn.classList.add('show');
              } else {
                  scrollToTopBtn.classList.remove('show');
              }
          });

          scrollToTopBtn.addEventListener('click', function(e) {
              e.preventDefault();
              window.scrollTo({
                  top: 0,
                  behavior: 'smooth'
              });
          });
      }
  });
  document.getElementById('toggle-menu').addEventListener('click', function() {
  document.querySelector('aside').classList.toggle('active');
});

  </script>
</body>
</html>